### ISSUE TITLE
agent使用sproto后好像不能正常发送数据给客户端

### ISSUE THREAD

**Issue by mikewu86** [hanxi/skynet-demo#11]
json是正常的。但是改成sproto之后就发不了。
![image](https://user-images.githubusercontent.com/31203217/159175008-fd2b32a8-31bf-4a97-bf44-988f4a8e9ac2.png)
回发数据会一直报错。
![image](https://user-images.githubusercontent.com/31203217/159175035-6817ce53-530f-4481-97f3-8e9312ab8d1b.png)
检查发现这几个数据都是存在的，fd也是一样的，请教如何解决这个问题啊？

**Comment by hanxi** [comment]
https://github.com/hanxi/skynet-demo/blob/master/service/ws_gate.lua#L181

这里加打印看看，还有result 的type是啥，是string吗？

**Comment by mikewu86** [comment]
加了，居然是number...

**Comment by hanxi** [comment]
那就是你的 request 打包函数有问题了

**Comment by mikewu86** [comment]
是的，处理错了。已解决。感谢感谢。
