### ISSUE TITLE
推送 如何处理

### ISSUE THREAD

**Issue by cloudfreexiao** [hanxi/skynet-demo#2]
我看了下 现在 m/s 处理 只是 针对 客户端 发送过来的数据 
在 游戏里 大量推送 是 服务器 发起的 比如 战斗 场景中
相比 前者 后者 压力 会 大很多 如果 所有推送都 经过 watchdog 再 转到 ws_agent 里 ？
想问下 对这种场景 有啥 好办法 能把 压力 分摊 出去吗

**Comment by hanxi** [comment]
forward 后，ws_agent 推送消息到 ws_gate 再转发给 客户端，没有经过 watchdog

**Comment by cloudfreexiao** [comment]
从 场景或 其他服务 里 如何 做 forward 到 ws_agent ？ 不太明白

**Comment by hanxi** [comment]
上面的回复我搞错 forward 了，forward 只是把客户端上行的协议自动转到对应的服务。服务器下行协议给客户端的话，只需要把协议发给 gate 即可。场景服务里可以记录玩家所在的 gate 。

**Comment by hanxi** [comment]
还是不建议其他服务推消息到 gate 转发，建议所有客户端消息都通过 agent 处理。其他服务推到 agent ，agent 推到 gate ，gate 推到客户端。

**Comment by cloudfreexiao** [comment]
我们也是这么做的 只不过 这里 有个 对 agent 生命周期的管理问题 我是用 广播来处理 当 agent 消失 有需要的 服务 做 剔除 不在 广播 不晓得  你们是 如何 处理 ？

**Comment by hanxi** [comment]
如果是一个玩家一个 agent 的话，管理 agent 就是管理在线玩家。玩家是否在线这份数据由一个地方管理，在线状态变化之后广播到需要监听这份数据的变化的服务就可以了。可以结合 `skynet.multicast` 和 `skynet.datacenter` 配合本地缓存来管理这份数据。

**Comment by cloudfreexiao** [comment]
嗯 我们是这么干的
