### ISSUE TITLE
注册失败

### ISSUE THREAD

**Issue by ZhouJiaZhi** [hanxi/skynet-demo#5]
https://www.lanqiao.cn/courses/2770
我第一次获取验证码就报这个错误了，貌似注册不了账号了
<img width="351" alt="截屏2020-12-24 下午7 17 34" src="https://user-images.githubusercontent.com/20750357/103085455-b551d600-461c-11eb-8c0d-88b023a47049.png">

**Comment by hanxi** [comment]
@ZhouJiaZhi 我问问平台那边是什么情况。

**Comment by hanxi** [comment]
@ZhouJiaZhi 你要么加下我微信？我的微信 base64 bWluZ2hhbnhp

 >这个要报下手机号让研发那边看看才知道 可能是网络不通发送了多条 被阿里云拦截了
