### ISSUE TITLE
ws_gate的最大连接数

### ISSUE THREAD

**Issue by ypengju** [hanxi/skynet-demo#8]
ws_gate中的maxclient限制在了单个slave服务中，导致每个限制是针对单个slave服务的，在master中是不是更合理一些？

**Comment by hanxi** [comment]
maxclient 确实是只限定了单个 slave 支持的最大客户端数量，如果要把 maxclient 设计为单个进程支持的最大客户端数量的话，也不是放在 master 中的，因为客户端数量只在 slave 中统计，所以需要用总数量除以 slave 的数量才是单个 slave 支持的最大数量。应该只需要改一行代码就能实现。

https://github.com/hanxi/skynet-demo/blob/master/service/ws_gate.lua#L193

maxclient = (conf.maxclient or 1024)//(conf.instance or 8)

这只是配置上的一个东西，两种方案都可以。

或者按照你说的把数量统计放到 master 也可以的，这样改动有点多， close 的时候 slave 要通知 master 扣数量。

**Comment by ypengju** [comment]
``` 
maxclient = (conf.maxclient or 1024)//(conf.instance or 8)
```
 这种似乎更好一点
